AWSTemplateFormatVersion: 2010-09-09
Resources:
    POLICY01:
        Type: 'AWS::IAM::Policy'
        Properties:
            PolicyName: 'TERRAFORM-0001-0007'
            Roles:
                - 'TERRAFORM-ROLE'
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -   Effect: 'Allow'
                        Action:
                            - 'lambda:AddPermission'
                            - 'lambda:CreateAlias'
                            - 'lambda:CreateFunction'
                            - 'lambda:DeleteAlias'
                            - 'lambda:DeleteFunction'
                            - 'lambda:DeleteFunctionConcurrency'
                            - 'lambda:GetAlias'
                            - 'lambda:GetFunction'
                            - 'lambda:GetFunctionConfiguration'
                            - 'lambda:GetPolicy'
                            - 'lambda:Invoke'
                            - 'lambda:InvokeAsync'
                            - 'lambda:ListAliases'
                            - 'lambda:ListVersionsByFunction'
                            - 'lambda:PublishVersion'
                            - 'lambda:PutFunctionConcurrency'
                            - 'lambda:RemovePermission'
                            - 'lambda:UpdateAlias'
                            - 'lambda:UpdateFunctionCode'
                            - 'lambda:UpdateFunctionConfiguration'
                            - 'lambda:CreateEventSourceMapping'
                            - 'lambda:DeleteEventSourceMapping'
                            - 'lambda:GetEventSourceMapping'
                            - 'lambda:ListEventSourceMappings'
                            - 'lambda:UpdateEventSourceMapping'
                        Resource:
                            - !Join
                                - ':'
                                -   - 'arn:aws:lambda'
                                    - !Ref 'AWS::Region'
                                    - '*:function:hello-travis'
                    -   Effect: 'Allow'
                        Action:
                            - 'lambda:GetAccountSettings'
                            - 'lambda:ListFunctions'
                            - 'lambda:ListTags'
                            - 'lambda:TagResource'
                            - 'lambda:UntagResource'
                        Resource:
                            - '*'
                    -   Effect: 'Allow'
                        Action:
                            - 'kms:CancelKeyDeletion'
                            - 'kms:CreateAlias'
                            - 'kms:CreateGrant'
                            - 'kms:CreateKey'
                            - 'kms:Decrypt'
                            - 'kms:DeleteAlias'
                            - 'kms:DeleteImportedKeyMaterial'
                            - 'kms:DescribeKey'
                            - 'kms:DisableKey'
                            - 'kms:DisableKeyRotation'
                            - 'kms:EnableKey'
                            - 'kms:EnableKeyRotation'
                            - 'kms:Encrypt'
                            - 'kms:GenerateDataKey'
                            - 'kms:GenerateDataKeyWithoutPlaintext'
                            - 'kms:GenerateRandom'
                            - 'kms:GetKeyPolicy'
                            - 'kms:GetKeyRotationStatus'
                            - 'kms:GetParametersForImport'
                            - 'kms:ImportKeyMaterial'
                            - 'kms:ListAliases'
                            - 'kms:ListGrants'
                            - 'kms:ListKeyPolicies'
                            - 'kms:ListKeys'
                            - 'kms:ListKeys'
                            - 'kms:ListResourceTags'
                            - 'kms:ListRetirableGrants'
                            - 'kms:PutKeyPolicy'
                            - 'kms:ReEncrypt'
                            - 'kms:RetireGrant'
                            - 'kms:RevokeGrant'
                            - 'kms:ScheduleKeyDeletion'
                            - 'kms:TagResource'
                            - 'kms:UntagResource'
                            - 'kms:UpdateAlias'
                            - 'kms:UpdateKeyDescription'
                        Resource:
                            - "*"
                    -   Effect: 'Allow'
                        Action:
                            - 'iam:GetRolePolicy'
                            - 'iam:PutRolePolicy'
                            - 'iam:DeleteRolePolicy'
                            - 'iam:AttachRolePolicy'
                            - 'iam:DetachRolePolicy'
                            - 'iam:ListAttachedRolePolicies'
                            - 'iam:ListInstanceProfilesForRole'
                            - 'iam:UpdateAssumeRolePolicy'
                            - 'iam:GetRole'
                            - 'iam:CreateRole'
                            - 'iam:DeleteRole'
                            - 'iam:UpdateRoleDescription'
                            - 'iam:CreatePolicy'
                            - 'iam:GetPolicy'
                            - 'iam:DeletePolicy'
                            - 'iam:ListPolicies'
                            - 'iam:PassRole'
                        Resource:
                            - 'arn:aws:iam::*:role/hello-travis'
                            - 'arn:aws:iam::*:policy/hello-travis'
                    -   Effect: 'Allow'
                        Action:
                            - 's3:ListBucket'
                        Resource:
                            - 'arn:aws:s3:::gbm-devops-*'
                    -   Effect: 'Allow'
                        Action:
                            - 's3:GetObject'
                            - 's3:PutObject'