AWSTemplateFormatVersion: 2010-09-09
Resources:
    POLICY01:
        Type: 'AWS::IAM::Policy'
        Properties:
            PolicyName: 'TERRAFORM-0001-0008'
            Users:
                - 'TRAVISCI'
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: 'Allow'
                      Action:
                          - 'lambda:*'
                      Resource:
                          - !Join
                              - ':'
                              -   - 'arn:aws:lambda'
                                  - !Ref 'AWS::Region'
                                  - '*:function:hello-travis'
                    - Effect: 'Allow'
                      Action:
                          - 'lambda:*'
                      Resource:
                          - '*'
                    - Effect: 'Allow'
                      Action:
                          - 'kms:*'
                      Resource:
                          - "*"
                    - Effect: 'Allow'
                      Action:
                          - 'iam:*'
                      Resource:
                          - 'arn:aws:iam::*:role/hello-travis'
                          - 'arn:aws:iam::*:policy/hello-travis'
                    - Effect: 'Allow'
                      Action:
                          - 's3:ListBucket'
                      Resource:
                          - 'arn:aws:s3:::gbm-devops-*'
                    - Effect: 'Allow'
                      Action:
                          - 's3:GetObject'
                          - 's3:PutObject'
                      Resource:
                         - 'arn:aws:s3:::gbm-devops-*/iac/terraform/core/hello-travis/*'